import {getLesson} from '../data/lessons.js';
import {commands} from '../data/commands.js';
import {esc,terminal,button} from './ui.js';

export function lessonConcept(t){const l=getLesson(t.id);return `<div class="lesson-depth" data-lesson="${esc(t.id)}"><h3>理解運作原理</h3><p>${esc(l.explanation)}</p></div>`;}
export function lessonCase(t){return `<div class="lesson-worked"><h3>案例推導與判讀</h3><p>${esc(getLesson(t.id).worked)}</p></div>`;}
export function lessonRecall(t){const r=getLesson(t.id).recall;return `<section class="lesson-recall"><h3>先想一想</h3><p>${esc(r.question)}</p><details><summary>查看參考解答</summary><p>${esc(r.answer)}</p></details></section>`;}
export function lessonCli(t){const l=getLesson(t.id);return `<div class="lesson-cli"><p>${esc(l.verification)}</p>${l.commandIds.map(id=>{const c=commands.find(c=>c.id===id);return c?`<h3>${esc(c.purpose)}</h3>${terminal(c)}<p>${esc(c.interpretation)}</p><small class="muted">${esc(c.version)}</small>`:'';}).join('')}${!l.commandIds.length?lessonRecall(t):''}</div>`;}
export function lessonCorrections(t){return getLesson(t.id).corrections.map(n=>`<aside class="callout lesson-correction"><strong>原書核對 · p. ${n.page} · ${esc(n.title)}</strong><p>${esc(n.text)}</p></aside>`).join('');}
export function lessonSources(t){const l=getLesson(t.id);return `<details class="lesson-sources"><summary>本章核對依據與延伸閱讀</summary><p>${l.basis==='pdf-aligned'?'依原 PDF 英文內容整理，補入運作推導與本站案例；相關原書勘誤另列。':'此主題為官方範圍補充，2024 年 PDF 未完整涵蓋，不標示為原書內容。'}</p>${l.chapters.map(c=>`<a href="#pdf?chapter=${c.id}&page=${c.start}&mode=parallel">原書 ${esc(c.number)} · ${esc(c.title)} · p. ${c.start}–${c.end}${c.scope==='extension'?'（延伸閱讀）':c.scope==='mixed'?'（含延伸內容）':''}</a>`).join('')}${l.official.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.name)} ↗</a>`).join('')}</details>`;}
export function lessonDiagram(t,step=0){const l=getLesson(t.id),active=Math.max(0,Math.min(3,step));return `<div class="lesson-diagram" aria-label="${esc(t.name)}運作流程"><ol class="lesson-flow">${l.stages.map((s,i)=>`<li class="${i===active?'active':''}" ${i===active?'aria-current="step"':''}><span>${i+1}</span><strong>${esc(s.label)}</strong><p>${esc(s.text)}</p></li>`).join('')}</ol><div class="lesson-flow-detail" aria-live="polite"><span class="badge">STEP ${active+1} / 4</span><p>${esc(l.stages[active].text)}</p>${button('追蹤下一步 →','packet','quiet')}</div></div>`;}
