import {getDomain,getTopic,topics} from '../data/catalog.js';
import {commands} from '../data/commands.js';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={dashboard:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',network:'M9 3h6v5H9z M2 16h6v5H2z M16 16h6v5h-6z M12 8v4M5 16v-4h14v4',layers:'m12 3 10 5-10 5L2 8z M2 12l10 5 10-5M2 16l10 5 10-5',route:'M5 3v12a4 4 0 0 0 4 4h10M15 15l4 4-4 4M2 6l3-3 3 3M5 10h10a4 4 0 0 0 4-4V3',server:'M3 3h18v7H3z M3 14h18v7H3z M7 6h1M7 17h1',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6z M8 12l3 3 5-6',code:'m8 5-6 7 6 7M16 5l6 7-6 7M14 2l-4 20',book:'M3 3h7l2 2 2-2h7v17h-7l-2 2-2-2H3z M12 5v17',arrow:'M4 12h16M14 6l6 6-6 6',check:'m5 12 4 4L20 5',clock:'M12 7v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',target:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0 M12 10v4',chart:'M3 3v18h18M7 16v-4M12 16V7M17 16V4',search:'M16 16l6 6M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',terminal:'m4 6 6 6-6 6M13 18h7',list:'M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1',flag:'M4 22V3c5-4 10 4 16 0v10c-6 4-11-4-16 0',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z',globe:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M2 12h20M12 2c-6 6-6 14 0 20 6-6 6-14 0-20',menu:'M3 6h18M3 12h18M3 18h18',copy:'M9 9h12v12H9z M15 5V2H2v13h3',download:'M12 2v13M7 10l5 5 5-5M3 17v5h18v-5',sun:'M12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0'};
export const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.book}"/></svg>`;
export const button=(text,action,cls='primary',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;
export const link=(text,href,cls='primary')=>`<a class="btn ${cls}" href="${href}">${text}</a>`;
export const empty=(title,description,action='')=>`<div class="empty">${icon('book')}<h3>${esc(title)}</h3><p>${esc(description)}</p>${action}</div>`;
export function terminal(command){return `<div class="terminal"><div class="terminal-bar"><span><i></i><i></i><i></i> ${esc(command.command)}</span><button class="copy" data-copy="${esc(command.id)}" aria-label="複製 ${esc(command.command)}">${icon('copy')} 複製</button></div><pre><code>${esc(command.example)}</code></pre></div>`;}
export function topology(topic,step=0){
 const nodes=topic.domain==='automation'?['應用程式','控制器','網路設備','狀態回報']:['PC1','SW1','SW2','R1'];
 const descriptions=topic.domain==='automation'?['應用程式描述需求與政策。','Northbound API 將需求交給控制器。','控制器經 southbound 介面協調設備。','設備回報狀態，確認政策與實際結果。']:['PC1 判斷目的地是否同子網；遠端目的先送預設閘道。','SW1 接收 frame，學習來源 MAC，在 VLAN 內查目的 MAC。','SW1 與 SW2 以 trunk 傳遞對應 VLAN 的訊框。','R1 終止 L2 frame，依目的 IP 查路由，再重新封裝到下一跳。'];
 return `<div class="topology" aria-label="封包旅程"><div class="network-nodes">${nodes.map((n,i)=>`${i?'<span class="wire"></span>':''}<div class="net-node ${i===step?'active':''}">${icon(i===0?'server':i===3?'route':'network')}<strong>${n}</strong></div>`).join('')}</div><div class="topology-caption"><span class="badge">STEP ${step+1} / 4</span><p>${descriptions[step]}</p>${button('追蹤下一步 →','packet','quiet')}</div></div>`;
}
export function questionCard(q,selected=[],{locked=false,exam=false}={}){
 const d=getDomain(q.domain);return `<section class="question card"><div class="question-meta"><span class="badge" style="--badge:${d?.color||'#338878'}">${esc(d?.name||q.domain)}</span><span>${esc(q.questionType)}</span><span>${esc(q.difficulty)}</span></div><h2>${esc(q.question).replace(/\n/g,'<br>')}</h2>${q.routes?`<div class="table-wrap"><table><thead><tr><th>Code</th><th>Prefix</th><th>AD / Metric</th><th>Next hop</th></tr></thead><tbody>${q.routes.map(r=>`<tr><td>${r.code}</td><td>${r.prefix}</td><td>[${r.ad}/${r.metric}]</td><td>${r.nextHop}</td></tr>`).join('')}</tbody></table></div>`:''}<p class="muted">${q.correctAnswer.length>1?`請選擇 ${q.correctAnswer.length} 個答案；需全部正確才計分。`:'請選擇一個答案。'}${exam?' 考試中不顯示解析。':''}</p><div class="options">${q.options.map((o,i)=>`<label class="option ${selected.includes(o.id)?'selected':''} ${locked&&q.correctAnswer.includes(o.id)?'correct':''} ${locked&&selected.includes(o.id)&&!q.correctAnswer.includes(o.id)?'incorrect':''}"><input type="${q.correctAnswer.length>1?'checkbox':'radio'}" name="answer" value="${esc(o.id)}" ${selected.includes(o.id)?'checked':''} ${locked?'disabled':''}><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span>${locked&&q.correctAnswer.includes(o.id)?icon('check'):''}</label>`).join('')}</div></section>`;
}
export function answerExplanation(q,answer,correct){
 const labels=ids=>ids.length?ids.map(id=>q.options.find(o=>o.id===id)?.text||id).join('；'):'未作答';
 const t=getTopic(q.topic);
 return `<section class="feedback card ${correct?'success':'failure'}" aria-live="polite"><div class="feedback-title">${icon(correct?'check':'flag')}<h2>${correct?'答對了，觀念更穩固一步。':'先釐清觀念，再試一次。'}</h2></div><dl><dt>你的答案</dt><dd>${esc(labels(answer))}</dd><dt>正確答案</dt><dd>${esc(labels(q.correctAnswer))}</dd><dt>結果</dt><dd>${correct?'正確':'錯誤 / 未作答'}</dd><dt>觀念 · 為什麼正確</dt><dd>${esc(q.explanation)}</dd><dt>為什麼其他答案錯</dt><dd><ul>${q.options.filter(o=>!q.correctAnswer.includes(o.id)).map(o=>`<li><strong>${esc(o.text)}</strong>：${esc(q.wrongAnswerExplanation?.[o.id]||'與題目要求的條件不符，請對照解析。')}</li>`).join('')}</ul></dd><dt>CCNA 重點</dt><dd>${esc(t?.key||q.explanation)}</dd><dt>相關指令</dt><dd>${q.commands.map(id=>{const c=commands.find(c=>c.id===id);return c?`<a class="code-link" href="#cli?q=${encodeURIComponent(c.command)}">${esc(c.command)}</a>`:'';}).join(' ')}</dd><dt>相關章節</dt><dd>${t?`<a href="#topic/${t.id}">${esc(t.en)} · ${esc(t.name)} →</a>`:''}</dd></dl></section>`;
}
export function domainBars(stats){return `<div class="domain-bars">${Object.entries(stats).length?'':''}${['fundamentals','access','connectivity','services','security','automation'].map(id=>{const d=getDomain(id),s=stats[id],rate=s?.total?Math.round(s.correct/s.total*100):0;return `<div class="bar-row"><div><span>${d.name}</span><strong>${s?.total?rate+'%':'尚未練習'}</strong></div><div class="track"><span style="width:${rate}%;background:${d.color}"></span></div><small>${s?.total?`${s.correct} / ${s.total} 題答對`:'完成練習後顯示表現'}</small></div>`;}).join('')}</div>`;}
export function topicCards(items,state){return `<div class="topic-grid">${items.map(t=>`<a class="card topic-card" href="#topic/${t.id}"><div class="eyebrow">${esc(getDomain(t.domain).name)} <span>${state.completed.includes(t.id)?'✓ 已完成':t.minutes+' MIN'}</span></div><h3>${esc(t.en)}</h3><p class="topic-chinese">${esc(t.name)}</p><p>${esc(t.concept)}</p><span class="text-link">進入章節 ${icon('arrow')}</span></a>`).join('')}</div>`;}
export const topicSelect=(value='',domain='')=>`<option value="">全部主題</option>${topics.filter(t=>!domain||t.domain===domain).map(t=>`<option value="${t.id}" ${t.id===value?'selected':''}>${esc(t.en)} · ${esc(t.name)}</option>`).join('')}`;
